version: "3"

services:
  mariadb:
    container_name: "mariadb"
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: check
      MARIADB_USER: username
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password